export const mockDataTeam = [
  //   {
  //     id: 1,
  //     name: "Jon Snow",
  //     gender: "Male",
  //     birthdate: "27/10/1989",
  //     email: "johnsnow@gmail.com",
  //     phone: "(665)121-5445",
  //     access: "admin",
  //     taskdone: 6,
  //   },
  //   {
  //     id: 2,
  //     name: "James Pitt",
  //     gender: "Male",
  //     birthdate: "27/11/1992",
  //     email: "jamespitt@gmail.com",
  //     phone: "(665)343-9953",
  //     access: "user",
  //     taskdone: 5,
  //   },
  //   {
  //     id: 3,
  //     name: "Mary Gabriella",
  //     gender: "Female",
  //     birthdate: "02/07/1993",
  //     email: "marymay@gmail.com",
  //     phone: "(665)078-5672",
  //     access: "user",
  //     taskdone: 5,
  //   },
  //   {
  //     id: 4,
  //     name: "Will Doofinsmirtz",
  //     gender: "Male",
  //     birthdate: "03/09/1988",
  //     email: "william@gmail.com",
  //     phone: "(646)122-1535",
  //     access: "user",
  //     taskdone: 4,
  //   },
  //   {
  //     id: 5,
  //     name: "David Shane",
  //     gender: "Male",
  //     birthdate: "04/05/1993",
  //     email: "davidshane@gmail.com",
  //     phone: "(445)123-4645",
  //     access: "user",
  //     taskdone: 4,
  //   },
  //   {
  //     id: 6,
  //     name: "Harry Bingsworth",
  //     gender: "Male",
  //     birthdate: "06/04/1991",
  //     email: "bingswarry@gmail.com",
  //     phone: "(665)163-2675",
  //     access: "user",
  //     taskdone: 2,
  //   },
  // ];
  {
    charts: [
      {
        name: "Chart of HR Department",
        data: [
          ["Day", "Finish", "Late", "Fail"],
          ["Mon", 6, 2, 1],
          ["Tue", 5, 3, 0],
          ["Wed", 6, 2, 1],
          ["Thu", 5, 4, 0],
          ["Fri", 3, 3, 0],
        ],
      },
      {
        name: "Chart of FrontEnd Department",
        data: [
          ["Day", "Finish", "Late", "Fail"],
          ["Mon", 3, 2, 0],
          ["Tue", 5, 1, 1],
          ["Wed", 6, 2, 1],
          ["Thu", 5, 0, 0],
          ["Fri", 4, 0, 0],
        ],
      },
      {
        name: "Chart of BackEnd Department",
        data: [
          ["Day", "Finish", "Late", "Fail"],
          ["Mon", 3, 2, 0],
          ["Tue", 2, 1, 0],
          ["Wed", 4, 1, 1],
          ["Thu", 3, 0, 0],
          ["Fri", 4, 0, 0],
        ],
      },
    ],
  },
];
